### ISSUE TITLE
Select icon rendering is broken

### ISSUE THREAD

**Issue by walkie** [FlorianWoelki/obsidian-icon-folder#25]
The rendering of search results in the icon select modal dialog seems to be broken. When the dialog first opens, the icons are displayed correctly. However, searching causes strange line breaks and for text and icons to be rendered on top of each other.

Here's a screenshot illustrating the issue:
<img width="645" alt="Folder Icon Rendering Bug" src="https://user-images.githubusercontent.com/1182255/147642459-a1b229d8-340e-444f-9a8b-c0b6fdada335.png">

OS and version info:
 * MacOS 11.6.2
 * Obsidian: v0.13.14
 * Icon Folder: 1.0.53

**Comment by ShahriarKh** [comment]
I was going to mention this! 
![image](https://user-images.githubusercontent.com/31452340/147670780-ad763469-da78-4f73-978d-de1d514ac35b.png)

The solution is to put icon name inside a div (or another tag). This is because every icon has `display: flex` and without the div, every line becomes a row in the block.
![image](https://user-images.githubusercontent.com/31452340/147671138-8f2bd52c-98e5-4771-a7c2-24a5fd527e4a.png)

**Comment by FlorianWoelki** [comment]
Thank you for reporting this issue! It should be fixed with the new release of version [1.0.54](https://github.com/FlorianWoelki/obsidian-icon-folder/releases/tag/1.0.54).
