### ISSUE TITLE
Some icons are lost when plugin is disabled then reenabled

### ISSUE THREAD

**Issue by adamhl8** [FlorianWoelki/obsidian-icon-folder#47]
I'm reporting two bugs here. Here is a test vault that (mostly) reproduces the issues: [Test.zip](https://github.com/FlorianWoelki/obsidian-icon-folder/files/8327283/Test.zip)

I'm using the Font Awesome Pro 6.1.0 icon pack and the two icons included in the above vault are from that pack.

1. Some icons are lost when plugin is disabled then reenabled

In my vault, if I disable the plugin and reenable it, nearly half of my icons go away and I'm just left with the icon names instead. Changing the icon to the same one fixes it. Restarting Obsidian does not fix the broken icons.

In the linked test vault, the behavior is the same, except restarting Obsidian does fix the broken icon. I'm not sure why that's the case.

2. Some icons do not work at all

In the test vault, the icon on file `Test1` does not display. In my vault, there are several other icons that also just don't work.

**Comment by se-cung-syu-ngai** [comment]
I am having this same problem. There are also many icons inexplicably disappearing as well. I have had to go to the font awesome website and manually download the ones I need.

**Comment by Snaity** [comment]
I am also having this problem with icons inexplicably disappearing/not being able to re-add through the plugin. I believe I'm encountering it as an issue with Obsidian Sync on both mobile and desktop. When syncing a desktop vault and the remote vault, I had several disappear, and then all of the icons disappear from mobile despite being enabled. Icons are also not showing up on mobile for me to replace them. The icon names remain in the titles for me also and restarting does not help.

**Comment by Oblique82** [comment]
this is affecting me a lot -both mac and iOS - I have lost and reapplied my icon twice - I don't want to do it again

**Comment by se-cung-syu-ngai** [comment]
I have switched the folder path to .obsidian/icons, where the icon shortcodes plugin keeps their icons. I have simply deleted the packs included with the Icon Folder plugin since it doesn't make sense to keep two copies of the same icons, and loaded those icons into the Icon Folder plugin as custom icons. Now the loading messages keep reminding me that their preexisting packs no longer exist. (Quite annoying, but good news is that my icons have stopped randomly reverting to text!)
@FlorianWoelki you should consider speaking with @aidenlx about standardizing these icon packs so users don't have to download two copies of the same thing if they happen to use your two plugins.

**Comment by Cammagno** [comment]
> @FlorianWoelki you should consider speaking with @aidenlx about standardizing these icon packs so users don't have to download two copies of the same thing if they happen to use your two plugins.

I agree with this, setting a standard location for icons will be helpful for everybody

**Comment by FlorianWoelki** [comment]
> > @FlorianWoelki you should consider speaking with @aidenlx about standardizing these icon packs so users don't have to download two copies of the same thing if they happen to use your two plugins.
> 
> 
> 
> I agree with this, setting a standard location for icons will be helpful for everybody

I've tried to make it as compatible as possible. You can change the icon pack path of my plugin so it fits with other icon plugins.

**Comment by FlorianWoelki** [comment]
Should be fixed with the newest release.

**Comment by adamhl8** [comment]
@FlorianWoelki Still having this issue unfortunately.

**Comment by FlorianWoelki** [comment]
> @FlorianWoelki Still having this issue unfortunately. This **[vault](https://github.com/FlorianWoelki/obsidian-icon-folder/files/8402714/Test.zip)** reproduces both issues I described in my first comment.
> 
> 1. You can't set icon `Fo0` on the note `Test` at all.
> 2. You can set `FoCircleCheck` on note `Test2`, but after closing and reopening the vault the icon is lost.

Ok so the first problem is fixed with the latest commit. It will be fixed whenever I release a new version.

The second problem relies on the svg name. How did you import the icon? Did you just drop it into the folder directly or through the plugin? Because the plugin is actually transforming it into `CircleCheck`. Right now, it is named `circle-check` which is not recognized by the plugin atm.

**Comment by adamhl8** [comment]
Ah okay. Yeah I was just dropping them into the folder directly. Didn't realize they would be renamed when imported through the plugin. Once I do that it works fine of course. I appreciate the help with this. Thanks!
